;;(load-file "~/.emacs.d/ini/ruby.el")
(add-to-list 'load-path "~/.emacs.d/script")
;;(load-library "utils.el")
(load-library "evil-config.el")
(load-library "theme.el")
(load-library "python.el")
(load-library "autocomplete.el")
(load-library "ess-config.el")
(load-library "alias.el")
(load-library "ggtags-config.el")
